### ISSUE TITLE
Add a command to find unassigned PRs

### ISSUE THREAD

**Issue by jdm** [servo/crowbot#27]
We use the assignee for a PR in servo/servo to indicate who is responsible for reviewing the changes. We should add a command that finds all of the PRs with no assignee and reports the title and url, one per line.

**Comment by fmmartins** [comment]
Hi, will work on it :+1:

**Comment by jdm** [comment]
Great! Feel free to ask questions about anything that's confusing!

**Comment by fmmartins** [comment]
Got it! 

I think it would be better to abstract the `searchGithub` function, which currently is hardcoded to search within the `/issues` endpoint. 

Since I have to make a request to the `/pulls` endpoint, it would be cleaner to abstract away `searchGithub` and pass an argument with the desired endpoint! What are your thoughts on this?

**Comment by jdm** [comment]
Yep, sounds sensible.

**Comment by fmmartins** [comment]
Alright! Should I create a separate PR for that?

**Comment by jdm** [comment]
Separate commits in the same PR would be great.
